# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Install software from the Free Law Project with brew/homebrew "
REPO_LICENSE="GPL-2.0-only"
REPO_TOPICS=""

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/homebrew-freelawproject.git"
REPO_WEB_URL="https://github.com/chicks-net/homebrew-freelawproject"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="homebrew-freelawproject"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
)
