# .repo.toml

[about]
description = "Install software from the Free Law Project with brew/homebrew "
# topics = []
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:chicks-net/homebrew-freelawproject.git"
web_url = "https://github.com/chicks-net/homebrew-freelawproject"

[flags]
claude = true
claude-review = true
copilot-review = true
